# 📘 NumPy Complete Tutorial

## 1. Setup

In [1]:
import numpy as np

# Check the installed version
print("NumPy version:", np.__version__)

NumPy version: 2.0.2


## 2. Python Lists vs NumPy Arrays

Python lists can hold mixed data types (**heterogeneous**). NumPy arrays are **homogeneous** — all elements must be the same data type. If you mix types, NumPy will upcast them to a common type.

In [2]:
# A simple list of 10 numbers
create_list = list(range(10))
print("Items in the list:", create_list)

Items in the list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
def print_dtypes(l):
    for item in l:
        print(type(item))

print_dtypes(create_list)

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [4]:
# A heterogeneous list (mixed data types) - perfectly fine for a Python list
list_heterogeneous = [1, "2", "A", 3, {"A": 3, "B": 4}, 9, (10, 20, 30, 40), True]
print("Heterogeneous List:\n", list_heterogeneous)
print_dtypes(list_heterogeneous)

Heterogeneous List:
 [1, '2', 'A', 3, {'A': 3, 'B': 4}, 9, (10, 20, 30, 40), True]
<class 'int'>
<class 'str'>
<class 'str'>
<class 'int'>
<class 'dict'>
<class 'int'>
<class 'tuple'>
<class 'bool'>


In [5]:
# NumPy array with same datatypes
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a)
print("Type of a[0][0]:", type(a[0][0]))

[[1 2 3 4]
 [5 6 7 8]]
Type of a[0][0]: <class 'numpy.int64'>


In [6]:
# Try creating a NumPy array with mixed types (int + string)
b = np.array([[1, 2, 3],
              ["A", "B", "C"]])
print(b)
print("Type of b[0][0]:", type(b[0][0]))
# Notice: NumPy silently converted the integers to strings to keep the array homogeneous!

[['1' '2' '3']
 ['A' 'B' 'C']]
Type of b[0][0]: <class 'numpy.str_'>


## 3. Creating and Accessing Arrays

In [7]:
arr = np.array([
    [9.0, 8.0, 7.0],
    [6.0, 5.0, 4.0]
])

print(f"Number of dimensions = {arr.ndim}")
print(f"Shape of arr        = {arr.shape}")
print(f"Total items          = {arr.size}")
print(f"Data type            = {arr.dtype}")
arr

Number of dimensions = 2
Shape of arr        = (2, 3)
Total items          = 6
Data type            = float64


array([[9., 8., 7.],
       [6., 5., 4.]])

In [8]:
# Access every element with nested loops
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        print(f"Element at {i},{j} = {arr[i][j]}")

Element at 0,0 = 9.0
Element at 0,1 = 8.0
Element at 0,2 = 7.0
Element at 1,0 = 6.0
Element at 1,1 = 5.0
Element at 1,2 = 4.0


In [9]:
# Select an entire row
arr[0, :]

array([9., 8., 7.])

In [10]:
# Select an entire column
arr[:, 1]

array([8., 5.])

## 4. Special Types of Arrays

In [11]:
# Array of zeros
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# Array of ones, with a specific dtype
np.ones(5, dtype='int')

array([1, 1, 1, 1, 1])

In [13]:
# Array of zeros with a specific dtype
np.zeros(5, dtype='float')

array([0., 0., 0., 0., 0.])

In [14]:
# Array filled with a constant value
np.full((2, 2), 199)

array([[199, 199],
       [199, 199]])

In [15]:
# Identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [16]:
# Random integers between low (inclusive) and high (exclusive)
np.random.randint(low=-1, high=100, size=(3, 3))

array([[67, 38, 22],
       [66, 64, 12],
       [37, 73, 44]])

## 5. Random Numbers & `np.random.seed()`

`np.random.seed()` makes random number generation **reproducible** — using the same seed always produces the same sequence of "random" numbers, which is important for consistent experiments.

In [17]:
# 5x5 array from a normal distribution (mean=0, std=1), with a fixed seed
np.random.seed(10)
x = np.random.normal(0, 1, (5, 5))
x

array([[ 1.3315865 ,  0.71527897, -1.54540029, -0.00838385,  0.62133597],
       [-0.72008556,  0.26551159,  0.10854853,  0.00429143, -0.17460021],
       [ 0.43302619,  1.20303737, -0.96506567,  1.02827408,  0.22863013],
       [ 0.44513761, -1.13660221,  0.13513688,  1.484537  , -1.07980489],
       [-1.97772828, -1.7433723 ,  0.26607016,  2.38496733,  1.12369125]])

In [18]:
# Without setting the seed again, results differ every time this cell runs
x = np.random.normal(0, 1, (5, 5))
x

array([[ 1.67262221,  0.09914922,  1.39799638, -0.27124799,  0.61320418],
       [-0.26731719, -0.54930901,  0.1327083 , -0.47614201,  1.30847308],
       [ 0.19501328,  0.40020999, -0.33763234,  1.25647226, -0.7319695 ],
       [ 0.66023155, -0.35087189, -0.93943336, -0.48933722, -0.80459114],
       [-0.21269764, -0.33914025,  0.31216994,  0.56515267, -0.14742026]])

In [19]:
# Using a different seed value produces a different (but reproducible) sequence
np.random.seed(20)
x = np.random.normal(0, 1, (5, 5))
x

array([[ 0.88389311,  0.19586502,  0.35753652, -2.34326191, -1.08483259],
       [ 0.55969629,  0.93946935, -0.97848104,  0.50309684,  0.40641447],
       [ 0.32346101, -0.49341088, -0.79201679, -0.84236793, -1.27950266],
       [ 0.24571517, -0.0441948 ,  1.56763255,  1.05110868,  0.40636843],
       [-0.1686461 , -3.18970279,  1.12013226,  1.33277821, -0.24333877]])

In [20]:
# Reset back to seed=10 -> get the EXACT same numbers as our first seed(10) run
np.random.seed(10)
x = np.random.normal(0, 1, (5, 5))
x

array([[ 1.3315865 ,  0.71527897, -1.54540029, -0.00838385,  0.62133597],
       [-0.72008556,  0.26551159,  0.10854853,  0.00429143, -0.17460021],
       [ 0.43302619,  1.20303737, -0.96506567,  1.02827408,  0.22863013],
       [ 0.44513761, -1.13660221,  0.13513688,  1.484537  , -1.07980489],
       [-1.97772828, -1.7433723 ,  0.26607016,  2.38496733,  1.12369125]])

In [21]:
print("Shape of x is:", x.shape)

Shape of x is: (5, 5)


## 6. Array Indexing

Indexing in NumPy (like Python) starts from **0**. Negative indices count from the end.

In [22]:
x = np.array(["A", "B", "C", "D", "E", "F", "G"])
print("First element:", x[0])
print("Second element:", x[1])
print("Last element:", x[-1])
print("Second-to-last element:", x[-2])

First element: A
Second element: B
Last element: G
Second-to-last element: F


In [23]:
np.random.seed(10)
y = np.random.normal(0, 1, (2, 2))
y

array([[ 1.3315865 ,  0.71527897],
       [-1.54540029, -0.00838385]])

In [24]:
print("First row, first column:", y[0, 0])
print("Last row, last column:", y[-1, -1])

First row, first column: 1.331586504129518
Last row, last column: -0.008383849928522256


## 7. Array Slicing

Use slicing to access multiple elements at once: `array[start:stop:step]`.

In [25]:
# seeting the array x to be from 10 to 29
x = np.arange(10, 30)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [26]:
# Elements up to (not including) index 5
x[:5]

array([10, 11, 12, 13, 14])

In [27]:
# Elements from index 10 onward
x[10:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [28]:
# Elements from index 14 up to (not including) index 19
x[14:19]

array([24, 25, 26, 27, 28])

In [29]:
x[14:25:2]

array([24, 26, 28])

In [30]:
# Reverse the array
x[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

## 8. Mathematics on Arrays

In [31]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(a)

[[1 2 3]
 [4 5 6]]


In [32]:
# Scalar multiplication (broadcasting)
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [33]:
# Elementwise cosine
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [34]:
# Elementwise square root
np.sqrt(a.astype(float))

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [35]:
# Minimum along each column (axis=0) and each row (axis=1)
print("Column-wise min:", np.min(a, axis=0))
print("Row-wise min:", np.min(a, axis=1))

Column-wise min: [1 2 3]
Row-wise min: [1 4]


### Elementwise Arithmetic Between Two Arrays

In [36]:
p = np.array([[1, 2], [3, 4]], dtype=np.float64)
q = np.array([[5, 6], [7, 8]], dtype=np.float64)

In [37]:
# Elementwise sum - both forms are equivalent
print(p + q)
print(np.add(p, q))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [38]:
# Elementwise difference
print(p - q)
print(np.subtract(p, q))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [39]:
# Elementwise product (NOT matrix multiplication)
print(p * q)
print(np.multiply(p, q))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [40]:
# Elementwise division
print(p / q)
print(np.divide(p, q))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


## 9. Matrix Multiplication & Linear Algebra

In [41]:
m1 = np.ones((2, 3))
print("m1: \n", m1)

m2 = np.full((3, 2), 2.5)
print("m2: \n",m2)

mult = np.matmul(m1, m2)
print("matrix Multiplication Result: \n" ,mult)

m1: 
 [[1. 1. 1.]
 [1. 1. 1.]]
m2: 
 [[2.5 2.5]
 [2.5 2.5]
 [2.5 2.5]]
matrix Multiplication Result: 
 [[7.5 7.5]
 [7.5 7.5]]


In [42]:
# Determinant of the resulting matrix
np.linalg.det(mult)

np.float64(0.0)

### Vectors & the `.dot()` Method

In [43]:
x2 = np.array([[1, 2], [3, 4]])
y2 = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])


In [44]:
# Inner product of vectors - both forms are equivalent
print(v.dot(w))
print(np.dot(v, w))

219
219


In [45]:
# Matrix / vector product
print(x2.dot(v))
print(np.dot(x2, v))

[29 67]
[29 67]


In [46]:
# Matrix / matrix product
print(x2.dot(y2))
print(np.dot(x2, y2))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


## 10. Stacking and Concatenation

In [47]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

# Stack arrays vertically (row-wise)
np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

# Stack arrays horizontally (column-wise)
np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### `np.concatenate` with the `axis` Parameter

In [49]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
arr_3 = np.array(['A', 'B', 'C'])

np.concatenate([arr_1, arr_2, arr_3])

array(['1', '2', '3', '4', '5', '6', 'A', 'B', 'C'], dtype='<U21')

In [50]:
# Concatenation also works on 2-D arrays
matrix = np.array([["Alpha", "Beta", "Gamma"], ["Delta", "Epsilon", "Zeta"]])
print(matrix)
np.concatenate([matrix, matrix])

[['Alpha' 'Beta' 'Gamma']
 ['Delta' 'Epsilon' 'Zeta']]


array([['Alpha', 'Beta', 'Gamma'],
       ['Delta', 'Epsilon', 'Zeta'],
       ['Alpha', 'Beta', 'Gamma'],
       ['Delta', 'Epsilon', 'Zeta']], dtype='<U7')

In [51]:
# axis=0 -> stack rows on top of each other (vertical)
concatenated_axis_0 = np.concatenate([matrix, matrix], axis=0)
print(concatenated_axis_0)
print("Shape:", concatenated_axis_0.shape)

[['Alpha' 'Beta' 'Gamma']
 ['Delta' 'Epsilon' 'Zeta']
 ['Alpha' 'Beta' 'Gamma']
 ['Delta' 'Epsilon' 'Zeta']]
Shape: (4, 3)


In [52]:
# axis=1 -> place columns side by side (horizontal)
concatenated_axis_1 = np.concatenate([matrix, matrix], axis=1)
print(concatenated_axis_1)
print("Shape:", concatenated_axis_1.shape)

[['Alpha' 'Beta' 'Gamma' 'Alpha' 'Beta' 'Gamma']
 ['Delta' 'Epsilon' 'Zeta' 'Delta' 'Epsilon' 'Zeta']]
Shape: (2, 6)


### Combining Arrays of Different Dimensions

`np.concatenate` requires matching dimensions, but `np.vstack` / `np.hstack` can combine a 1-D array with a 2-D array.

In [53]:
x3 = np.array([9, 10, 11])
matrix2 = np.array([[12, 13, 14], [15, 16, 17]])
vstack_example = np.vstack([x3, matrix2])

print(vstack_example)
print("Shape of stacked array:", vstack_example.shape)

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
Shape of stacked array: (3, 3)


In [54]:
z = np.array([[0], [0]])
hstack_example = np.hstack([matrix2, z])

print(hstack_example)
print("Shape of stacked array:", hstack_example.shape)

[[12 13 14  0]
 [15 16 17  0]]
Shape of stacked array: (2, 4)


## 11. Practice Problems

Try these on your own to test your understanding:

1. Find the inverse of a matrix (`np.linalg.inv`)
2. Find the trace of a matrix (`np.trace`)
3. Add and subtract two matrices
4. Create a 1-D array and split it into three 1-D arrays (`np.split`)
5. Create a 10x10 2-D array and split it into two 2-D arrays (`np.split` with `axis`)

In [55]:
# Your code here
